### Ex7.11
2つのベクトルv1,v2 に対し、その両方を通る直線の指揮 ax + by = c を求める Python の関数 standard_form を書け。

In [3]:
from vectors import *

def standard_form(vector1, vector2):
    x1, y1 = vector1
    x2, y2 = vector2
    return ((y2 - y1),-(x2 - x1), x1*y2 - x2*y1)

### Ex7.14
do_collide(other_polygon)メソッドを書き、そのメソッドを持つ PolygonModelオブジェクトが、別のPolygonModel である other_polygon と衝突したかどうかを判定できるようにせよ。

In [4]:
class PolygonModel():
    def do_collide(self, other_polygon):
        # self の segments と other_polygon の segments について二重ループ
        # ループの中で segment 同士の does_intersect をチェック
        pass

### Ex7.19
3次元の点3つを入力として、それらの点を通る平面の標準形の方程式を返す Python の関数を書け。

In [5]:
# よくわからなかったので、本を見て写経
from vectors import *
def plane_equation(p1,p2,p3):
    parallel1 = subtract(p2,p1)
    parallel2 = subtract(p3,p1)
    a,b,c = cross(parallel1, parallel2)
    d = dot(p1, (a,b,c))
    return (a,b,c,d)

plane_equation((1,1,1),(3,0,0),(0,3,0))

(3, 3, 3, 9)

### Ex7.26

In [ ]:
import numpy as np

# 7,3,2節の解
matrix = np.array(((1,1,-1),(0,2,-1),(1,0,1)))
vector = np.array((-1,3,2))
np.linalg.solve(matrix,vector)

array([-1.,  3.,  3.])

In [ ]:
# 逆行列を求める
inv_matrix = np.linalg.inv(matrix)
# 元の行列とかけると単位行列となる(inv_matrix @ matrix でも計算できる)
np.matmul(inv_matrix, matrix)

array([[ 1.00000000e+00,  1.11022302e-16, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [12]:
# 右辺に逆行列をかける
np.matmul(inv_matrix, vector)

array([-1.,  3.,  3.])